application: ai2portfolio
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /apps
  static_dir: apps
- url: /apps2
  static_dir: apps2
- url: /quizly
  static_dir: quizly
- url: /starterApps
  static_dir: starterApps
- url: /screensteps
  static_dir: screensteps
- url: /apps/amazon
  static_dir: amazon  
- url: /assets
  static_dir: assets
- url: /images
  static_dir: images
- url: /assets/css
  static_dir: assets/css
- url: /older
  static_dir: older
- url: /tutorial_files
  static_dir: tutorial_files    
- url: /
  script: app_controller.py
- url: /Admin
  script: app_controller.py
  login: admin
- url: /.*
  script: app_controller.py
   


